### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by burkmarr** [BiologicalRecordsCentre/indicia-reports#3]
Hi @johnvanbreda. Can you give me permission to push a branch and create pull request on this project?

**Comment by johnvanbreda** [comment]
@BirenRathod can you do this? I don't have access to the settings tab so presumably don't have enough privileges.

**Comment by BirenRathod** [comment]
is this for butterfly-monitoring site?

**Comment by burkmarr** [comment]
@BirenRathod it's for some eBMS reports which need to go in here (as agreed with John and Gary).

**Comment by BirenRathod** [comment]
@burkmarr 
If it is eBMS reports which you committed into indicia_reports folder, you just need to pull that reports into warehouse's brc_reports in modules folder.

**Comment by BirenRathod** [comment]
Sorry @burkmarr 
I have added you in the collaborator list, see if that helps.

**Comment by burkmarr** [comment]
Thanks @BirenRathod - that did it.
